### ISSUE TITLE
Cannot install if the AWS node does not have a public IP address.

### ISSUE THREAD

**Issue by glasschef** [chef-partners/omnibus-marketplace#6]
Chef Server cannot install if the AWS node does not have a public IP address. This causes issues if a customer needs to run their Chef server in a private IP address space.

**Comment by ryancragun** [comment]
This has been fixed and will be released with the next round of AWS images.  We currently [fallback to the private hostname and then local FQDN ](https://github.com/chef-partners/omnibus-marketplace/blob/master/files%2Fchef-marketplace-ctl-commands%2Fmarketplace%2Fsetup.rb#L87) if the public hostname is not available.
